# $FreeBSD: head/libexec/rtld-elf/tests/libpythagoras/Makefile 299094 2016-05-04 23:20:53Z ngie $

.include <bsd.own.mk>

LIB=		pythagoras
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf

SRCS=		pythagoras.c

LIBADD=		m

.include <bsd.lib.mk>
