#
# $FreeBSD: head/sys/modules/tests/callout_test/Makefile 299094 2016-05-04 23:20:53Z ngie $
#

.PATH: ${.CURDIR}/../../../tests/callout_test

KMOD=	callout_test
SRCS=	callout_test.c

#
# Enable full debugging
#
#CFLAGS += -g

.include <bsd.kmod.mk>
