# $FreeBSD: head/lib/clang/libllvmoption/Makefile 276479 2014-12-31 20:31:32Z dim $

.include <bsd.own.mk>

LIB=	llvmoption

SRCDIR=	lib/Option
SRCS=	Arg.cpp \
	ArgList.cpp \
	OptTable.cpp \
	Option.cpp

.include "../clang.lib.mk"
